// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyhxgxrsazgfilanxxgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5aHhneHJzYXpnZmlsYW54eGdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU0NDYyODUsImV4cCI6MjA1MTAyMjI4NX0._iYXzT2XbkXLzjY-Zy-xL1YadoIvGmD8Sl9M4mBdp1U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);